apiVersion: batch/v1
kind: Job
metadata:
  name: legalaid-webapp-job
spec:
  template:
    spec:
      containers:
      - name: legalaid-webapp-job
        image: yash5090/legalaid-webapp:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
