apiVersion: v1
kind: Service
metadata:
  name: legalaid-webapp-service
spec:
  selector:
    app: legalaid-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
