apiVersion: apps/v1
kind: Deployment
metadata:
  name: legalaid-webapp-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: legalaid-webapp
  template:
    metadata:
      labels:
        app: legalaid-webapp
    spec:
      containers:
        - name: legalaid-webapp
          image: yash5090/legalaid-webapp:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
